name: CI

on:
  push:
    branches:
      - main

jobs:
  echo_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo
        run: echo Ramtin
  date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Date
        run: date
